import AuthProvider from "@/components/AuthProvider"; 
import LoginForm from "@/pages/Login";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          {children} 
          <ToastContainer
            position="top-center" 
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        </body>
      </html>
    </AuthProvider>
  );
}
